[project]
name = "cg"
version = "0.1.0"
description = "Exercices for Computer Graphics Course"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.0", 
    "numpy>=2.2.3"
]
